apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator0-config
data:
  SPRING_APPLICATION_NAME: "AggregatorMicroservice-0"
  SERVER_PORT: "8090"
  
  MQTT_BROKER_URI: "tcp://mosquitto-0.mosquitto:1883"
