apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator4-config
data:
  SPRING_APPLICATION_NAME: "AggregatorMicroservice-4"
  SERVER_PORT: "8094"
  
  MQTT_BROKER_URI: "tcp://mosquitto-4.mosquitto:1883"