apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator2-config
data:
  SPRING_APPLICATION_NAME: "AggregatorMicroservice-2"
  SERVER_PORT: "8092"
  
  MQTT_BROKER_URI: "tcp://mosquitto-2.mosquitto:1883"