apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: postgres:15
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mainserver-secret
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mainserver-secret
                  key: DB_PASSWORD
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc2
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi