apiVersion: v1
kind: Secret
metadata:
  name: mainserver-secret
type: Opaque
stringData:
  DB_USERNAME: user
  DB_PASSWORD: pass

  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "pass"